[package]
name = "plexus"
version = "0.0.6"
authors = ["Sean Olson <olson.sean.k@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/olson-sean-k/plexus"
description = "3D mesh generation and manipulation."
keywords = ["graphics", "half-edge", "mesh", "topology"]

[package.metadata.docs.rs]
# Enable all featues so that trait implementations for types from commonly used
# linear algebra crates are shown.
all-features = true
rustdoc-args = ["--no-defaults",
                "--passes=collapse-docs",
                "--passes=strip-hidden",
                # Omitting this pass exposes documentation for aliased and
                # dereferenced types that are not re-exported. However, it also
                # generates a lot of spurious documentation. When enabled, the
                # documentation is more clean but incomplete. Topological views
                # are undocumented, for example.
                #
                # https://github.com/rust-lang/rust/issues/39437
                "--passes=strip-private",
                "--passes=strip-priv-imports",
                "--passes=unindent-comments"]

[badges]
appveyor = { repository = "olson-sean-k/plexus" }
travis-ci = { repository = "olson-sean-k/plexus" }

[[example]]
name = "viewer"
path = "examples/viewer/main.rs"

[lib]
name = "plexus"

[features]
default = ["geometry-nalgebra"]
geometry-cgmath = ["cgmath"]
geometry-nalgebra = ["alga", "nalgebra"]

[dependencies]
arrayvec = "0.3.*"
decorum = "0.0.5" # Unstable. Depend on exact version only.
derivative = "1.0.*"
itertools = "0.6.*"
num = "0.1.*"

alga = { version = "0.5.*", optional = true }
cgmath = { version = "0.15.*", optional = true }
nalgebra = { version = "0.13.*", optional = true }

[dev-dependencies]
gfx = "0.16.*"
gfx_device_gl = "0.14.*"
gfx_window_glutin = "0.18.*"
glutin = "0.10.*"
rand = "0.3.*"
